### ISSUE TITLE
Use ZIP or 7z for releases

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [JimDude7404/WSA-Windows-10#1]
RAR format is a propriety format.
LZMA2 (7z) outperforms it anyway.
Using Deflate or LZMA2 would be a better idea.

Thank you for your effort on this project.

**Comment by JimDude7404** [comment]
Hello! I chose .rar because most programs can read it (ex. Winarar, 7-Zip). I will however update the release later today to be a .7z 

Thanks!

**Comment by wefalltomorrow** [comment]
> Hello! I chose .rar because most programs can read it (ex. Winarar, 7-Zip). I will however update the release later today to be a .7z
> 
> Thanks!

Still a .rar?
